#!/bin/bash

[[ $# != 1 ]] && echo need a source file && exit

source=$1
target=${source%.cpp}.o

echo source $source
echo target $target

while :; do

	# Wait for file to be written to
	echo Wait...
	inotifywait -e modify $source -q

	# Build and run
	echo Go!
	clear
	make -j $target
	./target
done
