language: cpp

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - ggcov

script:
  - make --jobs 8
  - bash <(curl -s https://codecov.io/bash)
