language: cpp

script:
  - make CXX=clang-4.0
  - make clean
  - make CXX=g++-6
  - bash <(curl -s https://codecov.io/bash)

matrix:
  include:

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - g++-6
            - cppcheck
            - clang-tidy-4.0

    - os: osx
      osx_image: xcode8
