language: cpp

script:
  - make CXX=clang++-5.0
  - make clean
  - make CXX=g++-8 debug='-g --coverage'
  - bash <(curl -s https://codecov.io/bash)
  - cppcheck --enable=all .

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang++-5.0
            - g++-8
            - cppcheck
