dist: trusty
sudo: false
language: c++

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-4.0
    packages:
      - clang-4.0
      - g++-6
      - ggcov

script:
  - make --jobs 8
  - bash <(curl -s https://codecov.io/bash)
